### ISSUE TITLE
Unable to submit data with ajax

### ISSUE THREAD

**Issue by adamgajzlerowicz** [getgrav/grav-plugin-star-ratings#3] opened 2016-05-12 23:10 UTC
When plugin makes an attempt to submit the data - fails. From the dev console I can see that it tries to open the following link:

`POST http://localhost/blog/star-ratings.json/nonce:6061864bbd08e22dea2371636413e5c4`

It comes back with a

 500 error:

{"error":{"type":"RuntimeException","message":"Page Not Found","file":"\/var\/www\/html\/blog\/system\/src\/Grav\/Common\/Grav.php","line":177}}

![screenshot-3](https://cloud.githubusercontent.com/assets/675615/15233238/0db77260-189f-11e6-8298-0f8d848ae5ba.png)

**Comment by rhukster** [comment] 2016-05-12 23:54
is your site located in `/blog` directory?  

I'm unable to replicate this.

**Comment by rhukster** [comment] 2016-05-12 23:58
BTW, i did discover another bug that I fixed in 1.0.3 (should be available soon), but it's not related to the add-vote path.

**Comment by PiXeL0815** [comment] 2016-06-19 12:49
Is there a solution for this problem? I am facing the same issue.

**Comment by flaviocopes** [comment] 2016-06-20 09:30
@PiXeL0815 are you running apache on windows? @adamgajzlerowicz and you?

If so, you configured the Grav param separator to ";" in the system configuration?

**Comment by PiXeL0815** [comment] 2016-06-20 10:02
No, It is running on Linux. I have also tried your suggestion but it didn't work.

**Comment by flaviocopes** [comment] 2016-06-20 11:07
Ok, no that is only for windows.

**Comment by flaviocopes** [comment] 2016-06-20 11:17
Cannot replicate. Does any of these suggestion help? http://learn.getgrav.org/troubleshooting/page-not-found

**Comment by PiXeL0815** [comment] 2016-06-20 13:16
I have tried and played around with these settings without luck. 
Every other site works. Some other plugins I have tested are working too.

**Comment by PiXeL0815** [comment] 2016-07-01 13:45
Can anyone give some hints? I would really like to use this plugin :(

The grav log gives me this message:

[2016-07-01 15:23:53] grav.CRITICAL: Page Not Found - Trace: #0 /var/www/grave/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Grav::Grav\Common{closure}(Object(Grav\Common\Grav)) #1 /var/www/grave/user/plugins/simplesearch/simplesearch.php(83): Pimple\Container->offsetGet('page') #2 [internal function]: Grav\Plugin\SimplesearchPlugin->onPagesInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #3 /var/www/grave/vendor/symfony/event-dispatcher/EventDispatcher.php(181): call_user_func(Array, Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #4 /var/www/grave/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #5 /var/www/grave/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPagesInitiali...', Object(RocketTheme\Toolbox\Event\Event)) #6 /var/www/grave/system/src/Grav/Common/Grav.php(449): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPagesInitiali...', NULL) #7 /var/www/grave/system/src/Grav/Common/Grav.php(280): Grav\Common\Grav->fireEvent('onPagesInitiali...') #8 /var/www/grave/index.php(38): Grav\Common\Grav->process() #9 {main} [] []

**Comment by flaviocopes** [comment] 2016-07-01 14:57
I could not replicate the issue. Zip your user/ folder and post it to me on gitter.im/flaviocopes and I'll try replicating the problem, to check if it's a grav thing or a server thing

**Comment by flaviocopes** [comment] 2016-07-01 16:35
After a while debugging this, for some reason the Error plugin missing was the cause of the problem. If any has this same issue, please check the Error plugin is installed.

**Comment by flaviocopes** [comment] 2016-07-01 16:41
I think the cause is that the plugin does not add its own page. So when voting, the onPageNotFound event is triggered, and because of how things work, if not handled by the Error plugin, an exception is triggered.

**Comment by tidiview** [comment] 2016-07-07 17:59
I am meeting the same issue: vote is possible but no memory of votes

`http://localhost/star-ratings.json/nonce:af4825f55fd8190fdd5c9d8d10599816` **404 not found**

Error plugin installed

**Comment by flaviocopes** [comment] 2016-07-08 11:30
Does Admin work in your site, for example? Just checking if it's not a "normal" 404 learn.getgrav.org/troubleshooting/page-not-found

**Comment by rhukster** [comment] 2017-07-18 22:10
Does appear that your routing is not working.

**Closed as completed by rhukster** 2017-07-18 22:10 UTC
Labels: bug
